### PR TITLE
Fix occupancy capped

### LINKED ISSUE #166: API: Relative occupancy in stats is capped at 1
See [the discussion](https://github.com/pooh-labs/eaterslab/pull/159#discussion_r432825960).

### PR DESCRIPTION
**Pull request by avan1235**
Closes #166

### CODE REVIEW

File: android/app/src/main/java/labs/pooh/eaterslab/repository/dao/OccupancyStatsDao.kt [hunk 1]
```diff
@@ -1,11 +1,15 @@
...
+import kotlin.math.min
 
 data class OccupancyStatsDao(
     var id: Int?,
     var timestamp: org.threeten.bp.OffsetDateTime,
     var occupancyRelative: Double
-)
+) {
+    val occupancyPercent: Int
+    get() = (min(1.0, occupancyRelative) * 100.0).toInt()
```
Comment (Rhantolq) [inline android/app/src/main/java/labs/pooh/eaterslab/repository/dao/OccupancyStatsDao.kt:12]: Does it mean that server side now always return uncapped occupancy?

Comment (avan1235) [reply android/app/src/main/java/labs/pooh/eaterslab/repository/dao/OccupancyStatsDao.kt:12]: Yes, it think it was the requested feature as for now we don't support roles in the API

Comment (kantoniak) [reply android/app/src/main/java/labs/pooh/eaterslab/repository/dao/OccupancyStatsDao.kt:12]: We *do** support roles.
